[package]
name = "seedvault"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
rpassword = "7.4.0"

[profile.release]
# Optimize for security and size
opt-level = 3
lto = true
codegen-units = 1
strip = true
